/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import db.DataHandler;
import db.DialogHandler;
import static game.Main.listNPC;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import type.NPC;

/**
 *
 * @author tom
 */
public class Day1_Form extends javax.swing.JFrame {

    Day1 d1;
    boolean object_available =false;
    InventoryDialog inv =  new InventoryDialog(this, true);
    int i = 0; //per continuare dialoghi

    //TODO spostare in DAY1
    ActionHandler1 actHandler = new ActionHandler1(this);
    
    //NPC
    NPC dolly,j_marple,corpse,lorrimer,a_bantry,haydock,b_blake = new NPC();
    
    List<String> npcListD =new ArrayList<String>();
    List<String> D_bantry,Jane_marple,Lorri,Corp,Arthur,Doc,Basil = new ArrayList<String>();
    
    File file;
    
    
    /**
     * Creates new form Day1_Form
     */
    public JPanel bgPanel[] = new JPanel[20];
    public JLabel bgLabel[] = new JLabel[20];

    //TODO FORSE si può fare senza creare array e creandoli manualmente ogni scena, come il BACKPACK         
    public JLabel textBox[] = new JLabel[10];
    public JTextArea textAreaBox[] = new JTextArea[10];
    public JTextArea textAreaBox2[] = new JTextArea[10];
    public JButton textButton[] = new JButton[10];
    public JButton continueDialogue[] = new JButton[10];
    public JRadioButton dialogueButton1[] = new JRadioButton[10];
    public JRadioButton dialogueButton2[] = new JRadioButton[10];
    public JRadioButton dialogueButton3[] = new JRadioButton[10];
    public JRadioButton dialogueButton4[] = new JRadioButton[10];
    public JRadioButton dialogue2Button1[] = new JRadioButton[10];
    public JRadioButton dialogue2Button2[] = new JRadioButton[10];
    public JRadioButton dialogue2Button3[] = new JRadioButton[10];
    public JRadioButton dialogue2Button4[] = new JRadioButton[10];


    public JLabel detectiveDestra[] = new JLabel[10];
    public JLabel detectiveSinistra[] = new JLabel[10];
    public JLabel icon[] = new JLabel[10];

    ArrayList<String> list = new ArrayList<String>();

    public Day1_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        continua1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        background1.setBackground(new java.awt.Color(0, 0, 0));
        background1.setForeground(new java.awt.Color(255, 255, 255));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Dimora della famiglia Bantry");
        jTextField1.setBorder(null);
        background1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Californian FB", 3, 48)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("St. Mary Mead,   10 Ottobre 1982");
        jTextField2.setBorder(null);
        background1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 677, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Gossington Hall");
        jTextField3.setBorder(null);
        background1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 329, -1));

        continua1.setBackground(new java.awt.Color(0, 0, 0));
        continua1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        continua1.setForeground(new java.awt.Color(255, 255, 255));
        continua1.setText("Continua");
        continua1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        continua1.setContentAreaFilled(false);
        continua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continua1ActionPerformed(evt);
            }
        });
        background1.add(continua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continua1ActionPerformed
        try {
            generateScenes();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Day1_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Day1_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        background1.setVisible(false);
        bgPanel[1].setVisible(true);
    }//GEN-LAST:event_continua1ActionPerformed

    //TODO SPOSTARE IN DAY 1
    public void goToScene1() {
        bgPanel[2].setVisible(false);
        bgPanel[1].setVisible(true);
    }

    public void goToScene2() {
        bgPanel[1].setVisible(false);
        bgPanel[2].setVisible(true);
    }

    public void goToScene2From1Floor() {
        bgPanel[4].setVisible(false);
        bgPanel[2].setVisible(true);
    }

    public void goToScene2FromLRoom() {
        bgPanel[3].setVisible(false);
        bgPanel[2].setVisible(true);
    }

    public void goToScene3() {
        bgPanel[2].setVisible(false);
        bgPanel[3].setVisible(true);
    }

    public void goToScene4() {
        bgPanel[2].setVisible(false);
        bgPanel[4].setVisible(true);
    }

    public void goToScene4FromScene5() {
        bgPanel[5].setVisible(false);
        bgPanel[4].setVisible(true);
    }

    public void goToScene5() {
        bgPanel[4].setVisible(false);
        bgPanel[5].setVisible(true);
    }

    public void goToScene6() {
        bgPanel[4].setVisible(false);
        bgPanel[6].setVisible(true);
    }

    public void goToScene6FromScene4() {
        bgPanel[6].setVisible(false);
        bgPanel[4].setVisible(true);
    }

    public void observeScene1() {
        textBox[2].setVisible(true);
        textAreaBox[2].setVisible(true);
        textButton[2].setVisible(true);
        //TODO file
        textAreaBox[2].setText("Da qui sembra portare alla sala da pranzo di Gossington Hall.");
    }

    public void observeScene3() {
        textBox[2].setVisible(true);
        textAreaBox[2].setVisible(true);
        textButton[2].setVisible(true);
        //TODO file
        textAreaBox[2].setText("Da qui sembra portare al soggiorno.");
    }

    public void observeScene5() {
        textBox[4].setVisible(true);
        textAreaBox[4].setVisible(true);
        textButton[4].setVisible(true);
        //TODO file
        textAreaBox[4].setText("Questo sembra essere lo studio del signor Bantry.");
    }

    public void observeScene6() {
        textBox[4].setVisible(true);
        textAreaBox[4].setVisible(true);
        textButton[4].setVisible(true);
        //TODO file
        textAreaBox[4].setText("Di qui c'è l'imponente biblioteca di Gossington Hall.");
    }

    public void observeDollyBantry() {
        observeNPC(1,dolly,"d_bantry");
    }

    public void observeJaneMarple() {
        observeNPC(1,j_marple,"j_marple");       
    }

    public void observeLorrimer() {
        observeNPC(3,lorrimer,"lorrimer");                 
    }
    
    

    public void talkDollyBantry() throws IOException {
        readFile("d_bantry.txt");
        D_bantry = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogLeft(1,"/IconDollyB.png","d_bantry",D_bantry);
    }
    public void choice1(int bgNum, String npcName, String filename) throws FileNotFoundException, IOException {
        i=0;
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);       
        readFile(filename);
        
        npcListD = DialogHandler.SelectDialogOption(file, DialogHandler.FIRST_DIALOG_START, DialogHandler.FIRST_DIALOG_END);
        System.out.println(npcListD.get(i));
        textAreaBox[bgNum].setText(npcListD.get(i));
        textAreaBox2[bgNum].setText(npcListD.get(i+1));
        textButton[bgNum].setActionCommand("continueDialog" + bgNum);
        textButton[bgNum].setText("Continua");
    }

    public void choice2(int bgNum, String npcName,String filename) throws IOException {
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        readFile(filename);
        
        npcListD = DialogHandler.SelectDialogOption(file, DialogHandler.SECOND_DIALOG_START, DialogHandler.SECOND_DIALOG_END);
        System.out.println(npcListD.get(i));
        textAreaBox[bgNum].setText(npcListD.get(i));
        textAreaBox2[bgNum].setText(npcListD.get(i+1));
        textButton[bgNum].setActionCommand("continueDialog" + bgNum);
        textButton[bgNum].setText("Continua");     
    }
    public void choice3(int bgNum, String npcName,String filename) throws IOException {
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        readFile(filename);
       
        npcListD = DialogHandler.SelectDialogOption(file, DialogHandler.THIRD_DIALOG_START, DialogHandler.THIRD_DIALOG_END);
        System.out.println(npcListD.get(i));
        textAreaBox[bgNum].setText(npcListD.get(i));
        textAreaBox2[bgNum].setText(npcListD.get(i+1));
        textButton[bgNum].setActionCommand("continueDialog" + bgNum);
        textButton[bgNum].setText("Continua");
        
    }

    public void choice4(int bgNum, String npcName,String filename) throws IOException {
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        readFile(filename);
        npcListD = DialogHandler.SelectDialogOption(file, DialogHandler.FORTH_DIALOG_START, DialogHandler.FORTH_DIALOG_END);
        System.out.println(npcListD.get(i));
        textAreaBox[bgNum].setText(npcListD.get(i));
        textAreaBox2[bgNum].setText(npcListD.get(i+1));
        textButton[bgNum].setActionCommand("continueDialog" + bgNum);
        textButton[bgNum].setText("Continua");
    }

    public void talkJaneMarple() throws IOException {
        readFile("j_marple.txt");
        Jane_marple = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogRight(1,"/IconMarple.png","j_marple",Jane_marple);
    }

    public void talkLorrimer() throws IOException {
        readFile("lorrimer.txt");
        Lorri = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogLeft(3,"/IconLorrimer.png","lorrimer",Lorri);
        
        

    }
    
    public void observeBasil() {
       observeNPC(5,b_blake,"b_blake");
    }

    public void talkBasil() throws IOException {
        readFile("b_blake.txt");
        Basil = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogLeft(5,"/IconBlake.png","b_blake",Basil);
    }
    
    public void observeABantry() {
        observeNPC(5,a_bantry,"a_bantry");  
    }

    public void talkABantry() throws IOException {
        readFile("a_bantry.txt");
        Arthur = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogRight(5,"/IconArthur.png","a_bantry",Arthur);
    }
    
    public void observeHaydoc() {
        observeNPC(6,haydock,"haydock");  
    }

    public void talkHaydoc() throws IOException {
        readFile("haydock.txt");
        Doc = DialogHandler.SelectDialogOption(file, DialogHandler.DIALOG_OPTION_START, DialogHandler.DIALOG_OPTION_END);
        talkDialogRight(6,"/IconDoc.png","haydock",Doc);
        inv.getItem_1().setIcon(new ImageIcon(getClass().getResource("/doc_autopsia.png")));
        inv.getItem_1().setText("");
    }

    public void observeBody() {
        observeNPC(6,corpse,"corpse");  
    }

    public void analizeBody() {
        textBox[6].setVisible(true);
        textButton[6].setVisible(true);
        textAreaBox2[6].setVisible(true);
        textAreaBox2[6].setText("Ispezionando il cadavere , hai ottenuto ABITO BIANCO");
        inv.getItem_2().setIcon(new ImageIcon(getClass().getResource("/dress1.png")));
        inv.getItem_2().setText("");
        textButton[6].setText("Chiudi");
        textButton[6].setActionCommand("continueTextScene" + 6);
   
    }

    public void closeTextBox(int bgNum) {
        textBox[bgNum].setVisible(false);
        textAreaBox[bgNum].setVisible(false);
        textAreaBox2[bgNum].setVisible(false);
        textButton[bgNum].setVisible(false); 
        detectiveDestra[bgNum].setVisible(false);
        detectiveSinistra[bgNum].setVisible(false);
        icon[bgNum].setVisible(false);
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
         
        
    }
    public void observeNPC(int bgNum,NPC npc,String npcName){
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        detectiveDestra[bgNum].setVisible(false);
        detectiveSinistra[bgNum].setVisible(false);
        textAreaBox[bgNum].setVisible(true);
        icon[bgNum].setVisible(false);
        textBox[bgNum].setVisible(true);
        textAreaBox2[bgNum].setVisible(true);
        textButton[bgNum].setVisible(true);
        //TODO file
        npc = DataHandler.NpcFinder(listNPC, npcName);
        textAreaBox[bgNum].setText(npc.getName() + " " + npc.getSurname());
        textAreaBox2[bgNum].setText(npc.getDescription());
        textButton[bgNum].setActionCommand("continueTextScene" + bgNum);
    }

    public void continueDialog(int bgNum) {
        
        i=i+2;
        
        System.out.println("CONTINUADIALOGO");
        if (i < npcListD.size() ) {
            textAreaBox[bgNum].setText(npcListD.get(i));
            textAreaBox2[bgNum].setText(npcListD.get(i+1));
            
        } else {
            textButton[bgNum].setText("Chiudi");
            textButton[bgNum].setActionCommand("continueTextScene" + bgNum);
            closeTextBox(bgNum);
        }
        
    }
    
    
    public void talkDialogRight(int bgNum,String icona, String input,List<String> npcName) throws IOException{
        i = 0;
        detectiveSinistra[bgNum].setVisible(false);
        icon[bgNum].setVisible(true);
        setIcon(bgNum, icona);
        textButton[bgNum].setVisible(true);
        textBox[bgNum].setVisible(true);
        textAreaBox[bgNum].setVisible(true);
        textAreaBox2[bgNum].setVisible(true);
        dialogueButton1[bgNum].setVisible(true);
        dialogueButton2[bgNum].setVisible(true);
        dialogueButton3[bgNum].setVisible(true);
        dialogueButton4[bgNum].setVisible(true);
        detectiveDestra[bgNum].setVisible(true);
        dialogueButton1[bgNum].setSelected(false);
        dialogueButton2[bgNum].setSelected(false);
        dialogueButton3[bgNum].setSelected(false);
        dialogueButton4[bgNum].setSelected(false);
        textAreaBox[bgNum].setText("");
        textAreaBox2[bgNum].setText("");
        dialogueButton1[bgNum].setText(npcName.get(0));
        dialogueButton2[bgNum].setText(npcName.get(1));
        dialogueButton3[bgNum].setText(npcName.get(2));
        dialogueButton4[bgNum].setText(npcName.get(3));
        dialogueButton1[bgNum].addActionListener(actHandler);
        dialogueButton1[bgNum].setActionCommand("scelta1" + input);
        dialogueButton2[bgNum].addActionListener(actHandler);
        dialogueButton2[bgNum].setActionCommand("scelta2" + input);
        dialogueButton3[bgNum].addActionListener(actHandler);
        dialogueButton3[bgNum].setActionCommand("scelta3" + input);
        dialogueButton4[bgNum].addActionListener(actHandler);
        dialogueButton4[bgNum].setActionCommand("scelta4" + input);
           
    }
    
    
    public void talkDialogLeft(int bgNum, String icona,String input,List<String>npcName) throws IOException{
        i = 0;
        detectiveDestra[bgNum].setVisible(false);
        setIcon(bgNum, icona);
        icon[bgNum].setVisible(true);
        textBox[bgNum].setVisible(true);
        textAreaBox[bgNum].setVisible(true);
        textAreaBox2[bgNum].setVisible(true);
        dialogueButton1[bgNum].setVisible(true);
        dialogueButton2[bgNum].setVisible(true);
        dialogueButton3[bgNum].setVisible(true);
        dialogueButton4[bgNum].setVisible(true);
        dialogueButton1[bgNum].setSelected(false);
        dialogueButton2[bgNum].setSelected(false);
        dialogueButton3[bgNum].setSelected(false);
        dialogueButton4[bgNum].setSelected(false);
        textButton[bgNum].setVisible(true);
        detectiveSinistra[bgNum].setVisible(true);
        textAreaBox[bgNum].setText("");
        textAreaBox2[bgNum].setText("");
        dialogueButton1[bgNum].setText(npcName.get(0));
        dialogueButton2[bgNum].setText(npcName.get(1));
        dialogueButton3[bgNum].setText(npcName.get(2));
        dialogueButton4[bgNum].setText(npcName.get(3));
        dialogueButton1[bgNum].addActionListener(actHandler);
        dialogueButton1[bgNum].setActionCommand("scelta1" + input);
        dialogueButton2[bgNum].addActionListener(actHandler);
        dialogueButton2[bgNum].setActionCommand("scelta2" + input);
        dialogueButton3[bgNum].addActionListener(actHandler);
        dialogueButton3[bgNum].setActionCommand("scelta3" + input);
        dialogueButton4[bgNum].addActionListener(actHandler);
        dialogueButton4[bgNum].setActionCommand("scelta4" + input);
       
    }

    public void createScene(int bgNum, int x, int y, String bgFileName) {

        //panel
        bgPanel[bgNum] = new JPanel();
        bgPanel[bgNum].setBounds(0, 0, 1920, 1080);
        bgPanel[bgNum].setBackground(Color.black);
        bgPanel[bgNum].setLayout(null);
        bgPanel[bgNum].setVisible(false);

        //sfondo
        bgLabel[bgNum] = new JLabel();
        bgLabel[bgNum].setBounds(x, y, 1920, 1080);
        ImageIcon bgIcon = new ImageIcon(getClass().getResource(bgFileName));
        bgLabel[bgNum].setIcon(bgIcon);

        //backpack - inventory
        JButton backpack = new JButton();
        backpack.setBounds(1700, 10, 200, 200);
        backpack.setContentAreaFilled(false);
        ImageIcon arrowIcon = new ImageIcon(getClass().getResource("/backpack_inventory.png"));
        backpack.setBackground(null);
        backpack.setFocusPainted(false);
        backpack.setIcon(arrowIcon);
        backpack.addActionListener(actHandler);
        backpack.setActionCommand("openInventory");
        backpack.setBorderPainted(false);
        bgPanel[bgNum].add(backpack);

        this.add(bgPanel[bgNum]);
    }

      public void createTextBox(int bgNum, String npcName, String choice1, String choice2, String choice3, String choice4) {
        //TODO FARE PIù PICCOLA TEXT_BOX

        //creazione componenti
        textBox[bgNum] = new JLabel();
        textAreaBox[bgNum] = new JTextArea();
        textAreaBox2[bgNum] = new JTextArea();
        textButton[bgNum] = new JButton();
        continueDialogue[bgNum] = new JButton();
        detectiveDestra[bgNum] = new JLabel();
        detectiveSinistra[bgNum] = new JLabel();
        icon[bgNum] = new JLabel();
        
        ImageIcon detective = new ImageIcon(getClass().getResource("/detective.png"));
        ImageIcon detectiveflip = new ImageIcon(getClass().getResource("/detective_flip.png"));
        detectiveDestra[bgNum].setBounds(100, 200, 673, 873);
        detectiveSinistra[bgNum].setBounds(1000, 200, 673, 873);
        detectiveDestra[bgNum].setIcon(detectiveflip);
        detectiveSinistra[bgNum].setIcon(detective);
        ImageIcon boxIcon = new ImageIcon(getClass().getResource("/text_box.png"));
        textBox[bgNum].setIcon(boxIcon);
        textBox[bgNum].setBounds(300, 680, 1300, 320);
        textAreaBox[bgNum].setBackground(new Color(0, 0, 0, 0));
        textAreaBox[bgNum].setOpaque(false);
        textAreaBox[bgNum].setBounds(400, 740, 1000, 200);
        textAreaBox[bgNum].setFont(new java.awt.Font("Courier New", 0, 30));
        textAreaBox[bgNum].setForeground(Color.yellow);
        textAreaBox[bgNum].setBorder(null);
        textAreaBox[bgNum].setEditable(false);
        textAreaBox[bgNum].setWrapStyleWord(true);
        textAreaBox[bgNum].setLineWrap(true);
        textAreaBox2[bgNum].setBackground(new Color(0, 0, 0, 0));
        textAreaBox2[bgNum].setOpaque(false);
        textAreaBox2[bgNum].setBounds(400, 790, 1000, 200);
        textAreaBox2[bgNum].setFont(new java.awt.Font("Courier New", 0, 30));
        textAreaBox2[bgNum].setForeground(Color.white);
        textAreaBox2[bgNum].setBorder(null);
        textAreaBox2[bgNum].setEditable(false);
        textAreaBox2[bgNum].setWrapStyleWord(true);
        textAreaBox2[bgNum].setLineWrap(true);

        textButton[bgNum].setBackground(new Color(0, 0, 0));
        textButton[bgNum].setBounds(1420, 920, 64, 26);
        textButton[bgNum].setFont(new Font("Segoe UI", 2, 14)); // NOI18N
        textButton[bgNum].setForeground(new Color(255, 255, 255));
        textButton[bgNum].setText("Chiudi");
        textButton[bgNum].setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED,
                Color.lightGray, Color.white, Color.lightGray, Color.white));
        textButton[bgNum].setContentAreaFilled(false);
        textButton[bgNum].addActionListener(actHandler);
        textButton[bgNum].setActionCommand("continueTextScene" + bgNum);
        icon[bgNum].setBounds(1400, 790, 100, 100);

        //DIALOGHI A SCELTA
        dialogueButton1[bgNum] = new JRadioButton(choice1);
        dialogueButton2[bgNum] = new JRadioButton(choice2);
        dialogueButton3[bgNum] = new JRadioButton(choice3);
        dialogueButton4[bgNum] = new JRadioButton(choice4);

        dialogueButton1[bgNum].setBounds(395, 750, 600, 50);
        dialogueButton2[bgNum].setBounds(955, 750, 600, 50);
        dialogueButton3[bgNum].setBounds(395, 860, 600, 50);
        dialogueButton4[bgNum].setBounds(955, 860, 600, 50);
        dialogueButton1[bgNum].setSelected(false);
        dialogueButton2[bgNum].setSelected(false);
        dialogueButton3[bgNum].setSelected(false);
        dialogueButton4[bgNum].setSelected(false);
        dialogueButton1[bgNum].setForeground(Color.white);
        dialogueButton2[bgNum].setForeground(Color.white);
        dialogueButton3[bgNum].setForeground(Color.white);
        dialogueButton4[bgNum].setForeground(Color.white);
        dialogueButton1[bgNum].setBackground(new Color(0,0,0));
        dialogueButton1[bgNum].setOpaque(false);
        dialogueButton2[bgNum].setBackground(new Color(0,0,0));
        dialogueButton2[bgNum].setOpaque(false);
        dialogueButton3[bgNum].setBackground(new Color(0,0,0));
        dialogueButton3[bgNum].setOpaque(false);
        dialogueButton4[bgNum].setBackground(new Color(0,0,0));
        dialogueButton4[bgNum].setOpaque(false);
       

        dialogueButton1[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton2[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton3[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton4[bgNum].setFont(new Font("Courier New", 0, 28));

        dialogueButton1[bgNum].addActionListener(actHandler);
        dialogueButton1[bgNum].setActionCommand("scelta1" + npcName);
        dialogueButton2[bgNum].addActionListener(actHandler);
        dialogueButton2[bgNum].setActionCommand("scelta2" + npcName);
        dialogueButton3[bgNum].addActionListener(actHandler);
        dialogueButton3[bgNum].setActionCommand("scelta3" + npcName);
        dialogueButton4[bgNum].addActionListener(actHandler);
        dialogueButton4[bgNum].setActionCommand("scelta4" + npcName);

        ButtonGroup group = new ButtonGroup();
        group.add(dialogueButton1[bgNum]);
        group.add(dialogueButton2[bgNum]);
        group.add(dialogueButton3[bgNum]);
        group.add(dialogueButton4[bgNum]);

        //visibility
        
        textBox[bgNum].setVisible(false);
        textAreaBox[bgNum].setVisible(false);
        textAreaBox2[bgNum].setVisible(false);
        textButton[bgNum].setVisible(false);
        continueDialogue[bgNum].setVisible(false);
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        detectiveDestra[bgNum].setVisible(false);
        detectiveSinistra[bgNum].setVisible(false);
        icon[bgNum].setVisible(false);
        
        bgPanel[bgNum].add(icon[bgNum]);
        bgPanel[bgNum].add(dialogueButton4[bgNum]);
        bgPanel[bgNum].add(dialogueButton3[bgNum]);
        bgPanel[bgNum].add(dialogueButton2[bgNum]);
        bgPanel[bgNum].add(dialogueButton1[bgNum]);
        bgPanel[bgNum].add(continueDialogue[bgNum]);
        bgPanel[bgNum].add(textButton[bgNum]);
        bgPanel[bgNum].add(textAreaBox[bgNum]);
        bgPanel[bgNum].add(textAreaBox2[bgNum]);
        bgPanel[bgNum].add(textBox[bgNum]);
        bgPanel[bgNum].add(detectiveDestra[bgNum]);
        bgPanel[bgNum].add(detectiveSinistra[bgNum]);
    }
     



    public void setIcon(int bgNum, String Filename) {
        ImageIcon iconMini = new ImageIcon(getClass().getResource(Filename));
        icon[bgNum].setIcon(iconMini);  
    }

    public void readFile(String namefile) throws IOException {
       
        try {
            
            file = new File(DialogHandler.dir + "\\src\\main\\resources\\dialogs\\"+namefile);
            
        } catch (Exception e) {
            // Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

    }

    
    public void createArrowButton(int bgNum, int x, int y, String arrowFileName, String command) {

        ImageIcon arrowIcon = new ImageIcon(getClass().getResource(arrowFileName));

        JButton arrowButton = new JButton();
        arrowButton.setBounds(x, y, 150, 150);
        arrowButton.setBackground(null);
        arrowButton.setContentAreaFilled(false);
        arrowButton.setFocusPainted(false);
        arrowButton.setIcon(arrowIcon);
        arrowButton.addActionListener(actHandler);
        arrowButton.setActionCommand(command);
        arrowButton.setBorderPainted(false);

        bgPanel[bgNum].add(arrowButton);
    }

    public void createObject(int bgNum, int objx, int objy, int objWidth, int objHeight, String objFileName,
            String choice1Name, String choice2Name, String choice3Name, String choice1Command, String Choice2Command, String Choice3Command) {

         // CREATE POP MENU
        JPopupMenu popMenu = new JPopupMenu();
        // CREATE POP MENU ITEMS
        JMenuItem menuItem[] = new JMenuItem[4]; // Use [1],[2],[3]
        menuItem[1] = new JMenuItem(choice1Name);
        menuItem[1].addActionListener(actHandler);
        menuItem[1].setActionCommand(choice1Command);
        popMenu.add(menuItem[1]);

        menuItem[2] = new JMenuItem(choice2Name);
        menuItem[2].addActionListener(actHandler);
        menuItem[2].setActionCommand(Choice2Command);
        popMenu.add(menuItem[2]);

        menuItem[3] = new JMenuItem(choice3Name);
        menuItem[3].addActionListener(actHandler);
        menuItem[3].setActionCommand(Choice3Command);
        popMenu.add(menuItem[3]);

        // CREATE OBJECTS
        JLabel objectLabel = new JLabel();
        objectLabel.setBounds(objx, objy, objWidth, objHeight);
        //objectLabel.setOpaque(true);
        //objectLabel.setBackground(Color.blue);

        ImageIcon objectIcon = new ImageIcon(getClass().getResource(objFileName));
        objectLabel.setIcon(objectIcon);

        objectLabel.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    popMenu.show(objectLabel, e.getX(), e.getY());
                }
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }

        });

        bgPanel[bgNum].add(objectLabel);

    }

    public void generateScenes() throws FileNotFoundException, IOException {
        
        
        
        
        //SCENA 1 -> DINING ROOM
        createScene(1, 0, -10, "/diningroommod.png");
        createTextBox(1,"d_bantry","","","","");
        
        createArrowButton(1, 1750, 500, "/right_arrow.png", "goToCorridorFromDRoom");
        createObject(1, 200, 220, 200, 700, "", "Parla", "Osserva", "", "TalkDolly", "ObserveDolly", "");
        createObject(1, 1550, 210, 220, 700, "", "Parla", "Osserva", "", "TalkJane", "ObserveJane", "");
        bgPanel[1].add(bgLabel[1]);

        //SCENA 2 -> CORRIDOIO PIANO TERRA
        createScene(2, 352, 0, "/corridoio1.png");
        createObject(2, 620, 300, 150, 650, "", "Entra", "Osserva", "", "WestRoomCorridor1", "ObserveDiningRoom", "");
        createObject(2, 1215, 300, 150, 650, "", "Entra", "Osserva", "", "EastRoomCorridor1", "ObserveLivingRoom", "");
        createObject(2, 850, 350, 300, 500, "", "Sali al piano superiore", "", "", "StaircaseUP1", "", "");
        createTextBox(2, "josephine", "anvedi che fre-", "uWu", "kawaii", "Cock rating?");
        bgPanel[2].add(bgLabel[2]);

        //SCENA 3 -> LIVING ROOM 
        createScene(3, 0, -10, "/livingroom.png");
        createTextBox(3, "josephine", "anvedi che fre-", "uWu", "kawaii", "Cock rating?");
        createArrowButton(3, 10, 500, "/left_arrow.png", "goToCorridorFromLRoom");
        createObject(3, 250, 250, 200, 650, "", "Parla", "Osserva", "puntagli il ferro", "TalkLorrimer", "ObserveLorrimer", "");
        bgPanel[3].add(bgLabel[3]);

        //SCENA 4 -> CORRIDOIO PRIMO PIANO
        createScene(4, 352, 0, "/corridoio2.png");
        createTextBox(4, "josephine", "anvedi che fre-", "uWu", "kawaii", "Cock rating?");
        createArrowButton(4, 850, 850, "/down_arrow.png", "StaircaseDown1");
        createObject(4, 550, 300, 150, 650, "", "Entra", "Osserva", "", "WestRoomCorridor2", "ObserveLibrary", "");
        createObject(4, 1120, 300, 150, 650, "", "Entra", "Osserva", "", "EastRoomCorridor2", "ObserveStudy", "");
        bgPanel[4].add(bgLabel[4]);

        //SCENA 5 -> STUDIO
        createScene(5, 0, -10, "/studio.png");
        createTextBox(5, "josephine", "anvedi che fre-", "uWu", "kawaii", "Cock rating?");
        createArrowButton(5, 1750, 500, "/right_arrow.png", "goToCorridorFromStudy");
        createObject(5, 390, 250, 200, 700, "", "Parla", "Osserva", "", "TalkBasil", "ObserveBasil", "");
        createObject(5, 1350, 250, 220, 700, "", "Parla", "Osserva", "", "TalkABantry", "ObserveABantry", "");
        bgPanel[5].add(bgLabel[5]);

        //SCENA 6 -> BIBLIOTECA
        createScene(6, 0, -10, "/Library.png");
        createTextBox(6, "josephine", "anvedi che fre-", "uWu", "kawaii", "Cock rating?");
       
        createArrowButton(6, 10, 500, "/left_arrow.png", "goToCorridorFromLibrary");
        createObject(6, 250, 700, 600, 170, "", "Osserva", "Ispeziona", "", "ObserveBody", "AnalizeBody", "");
        createObject(6, 1000, 400, 220, 500, "", "Parla", "Osserva", "", "TalkHaydoc", "ObserveHaydoc", "");
        bgPanel[6].add(bgLabel[6]);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day1_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day1_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day1_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day1_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Day1_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1;
    private javax.swing.JButton continua1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    


}
