/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author tom
 */
public class Day_Form extends javax.swing.JFrame {

    /*
    * Istanza della classe manager
    */
    GameHandler gh;
 
    /*
    * variabile utilizzata per avanzare nei dialoghi
    */
    
    int i = 0;
 
    /*
    * Lista degli NPC utilizzata per prelevare i dialoghi
    */    
    List<String> npcListD = new ArrayList<>();        

    /**
     * Crea un array di panel che rappresentano le varie scene, uno per ogni scena
     */
    public JPanel bgPanel[] = new JPanel[25];

    /**
     * Array di label che fungono da sfondo
     */
    public JLabel bgLabel[] = new JLabel[25];

    /**
     * Label su cui compare il testo
     */
    public JLabel textBox[] = new JLabel[25];

    /**
     * Prima area di testo sovrapposta alla TextBox che contiene il testo
     */
    public JTextArea textAreaBox[] = new JTextArea[25];

    /**
     * Seconda area di testo sovrapposta alla TextBox che contiene il testo, per separare nome e testo durante dialogo
     */
    public JTextArea textAreaBox2[] = new JTextArea[25];

    /**
     * Bottoni che servono per continuare il dialogo o uscire dalla schermata di dialogo
     */
    public JButton textButton[] = new JButton[25];
    
    public JButton continueDialogue[] = new JButton[25];

    /**
     * 4 RadioButton per le quattro diverse scelte possibili
     */
    public JRadioButton dialogueButton1[] = new JRadioButton[25];
    
    public JRadioButton dialogueButton2[] = new JRadioButton[25];
 
    public JRadioButton dialogueButton3[] = new JRadioButton[25];
   
    public JRadioButton dialogueButton4[] = new JRadioButton[25];

    /**
     * Aree di testo utilizzate dalla funzione createStartDay()
     */
    public JTextField placeDescription1[] = new JTextField[23];

    public JTextField placeDescription2[] = new JTextField[23];
   
    public JTextField placeDescription3[] = new JTextField[23];
    
    public JTextField placeDescription4[] = new JTextField[23];

    /**
     * Bottone utilizzato dalla funzione createStartDay()
     */
    public JButton go[] = new JButton[23];

    /**
     * Label su cui compare il png del detective
     */
    public JLabel detectiveDestra[] = new JLabel[25];
    
    public JLabel detectiveSinistra[] = new JLabel[25];

    /**
     * Label usata per mostrare la mini icon nella schermata di dialogo
     */
    public JLabel icon[] = new JLabel[25];

      

    /**
     * Costruttore della classe Boundary
     * @param gh
     */
    public Day_Form(GameHandler gh) {
        initComponents();
        this.gh = gh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtTitle3 = new javax.swing.JTextField();
        txtTitle1 = new javax.swing.JTextField();
        txtTitle2 = new javax.swing.JTextField();
        cmdContinua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(null);

        txtTitle3.setEditable(false);
        txtTitle3.setBackground(new java.awt.Color(0, 0, 0));
        txtTitle3.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        txtTitle3.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle3.setText("Dimora della famiglia Bantry");
        txtTitle3.setBorder(null);
        bg.add(txtTitle3);
        txtTitle3.setBounds(720, 440, 436, 42);

        txtTitle1.setEditable(false);
        txtTitle1.setBackground(new java.awt.Color(0, 0, 0));
        txtTitle1.setFont(new java.awt.Font("Californian FB", 3, 48)); // NOI18N
        txtTitle1.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle1.setText("St. Mary Mead,   10 Ottobre 1982");
        txtTitle1.setBorder(null);
        bg.add(txtTitle1);
        txtTitle1.setBounds(610, 200, 677, 56);

        txtTitle2.setEditable(false);
        txtTitle2.setBackground(new java.awt.Color(0, 0, 0));
        txtTitle2.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        txtTitle2.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle2.setText("Gossington Hall");
        txtTitle2.setBorder(null);
        bg.add(txtTitle2);
        txtTitle2.setBounds(780, 360, 329, 56);

        cmdContinua.setBackground(new java.awt.Color(0, 0, 0));
        cmdContinua.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cmdContinua.setForeground(new java.awt.Color(255, 255, 255));
        cmdContinua.setText("Continua");
        cmdContinua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cmdContinua.setContentAreaFilled(false);
        cmdContinua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdContinuaActionPerformed(evt);
            }
        });
        bg.add(cmdContinua);
        cmdContinua.setBounds(900, 980, 64, 26);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("--------------------------------------------------------------------\n\nIl corpo di Ruby Keene, ragazza ormai deceduta, è stato\nritrovato a Gossington Hall, abitazione della famiglia Bantry.\nLa polizia arriva immediatamente sulla scena del crimine...\n\n--------------------------------------------------------------------");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        bg.add(jScrollPane1);
        jScrollPane1.setBounds(500, 600, 900, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Gestione del primo evento della classe
    */
    private void cmdContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdContinuaActionPerformed
        try {
            generateScenes();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Day_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Day_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        bg.setVisible(false);
        bgPanel[1].setVisible(true);
    }//GEN-LAST:event_cmdContinuaActionPerformed

    /**
     * Metodo che crea una generica scena
     * 
     * @param bgNum numero del panel da creare
     * @param x
     * @param y
     * @param bgFileName nome del file png per lo sfondo
     * @param actHandler indica quale sottoclasse di ActionHandler utilizzare
     */
    public void createScene(int bgNum, int x, int y, String bgFileName, ActionHandler actHandler) {

        //panel
        bgPanel[bgNum] = new JPanel();
        bgPanel[bgNum].setBounds(0, 0, 1920, 1080);
        bgPanel[bgNum].setBackground(Color.black);
        bgPanel[bgNum].setLayout(null);
        bgPanel[bgNum].setVisible(false);

        //sfondo
        bgLabel[bgNum] = new JLabel();
        bgLabel[bgNum].setBounds(x, y, 1920, 1080);
        ImageIcon bgIcon = new ImageIcon(getClass().getResource(bgFileName));
        bgLabel[bgNum].setIcon(bgIcon);

        //backpack - inventory
        JButton backpack = new JButton();
        backpack.setBounds(1700, 10, 200, 200);
        backpack.setContentAreaFilled(false);
        ImageIcon arrowIcon = new ImageIcon(getClass().getResource("/backpack_inventory.png"));
        backpack.setBackground(null);
        backpack.setFocusPainted(false);
        backpack.setIcon(arrowIcon);
        backpack.addActionListener(actHandler);
        backpack.setActionCommand("openInventory");
        backpack.setBorderPainted(false);
        bgPanel[bgNum].add(backpack);

        this.add(bgPanel[bgNum]);
    }

    /**
     * Crea una generica TextBox
     * 
     * @param bgNum numero panel dove crearla
     * @param actHandler indica quale sottoclasse di ActionHandler utilizzare
     */
    public void createTextBox(int bgNum, ActionHandler actHandler) {

        //creazione componenti
        textBox[bgNum] = new JLabel();
        textAreaBox[bgNum] = new JTextArea();
        textAreaBox2[bgNum] = new JTextArea();
        textButton[bgNum] = new JButton();
        continueDialogue[bgNum] = new JButton();
        detectiveDestra[bgNum] = new JLabel();
        detectiveSinistra[bgNum] = new JLabel();
        icon[bgNum] = new JLabel();

        ImageIcon detective = new ImageIcon(getClass().getResource("/detective.png"));
        ImageIcon detectiveflip = new ImageIcon(getClass().getResource("/detective_flip.png"));
        detectiveDestra[bgNum].setBounds(100, 200, 673, 873);
        detectiveSinistra[bgNum].setBounds(1000, 200, 673, 873);
        detectiveDestra[bgNum].setIcon(detectiveflip);
        detectiveSinistra[bgNum].setIcon(detective);
        ImageIcon boxIcon = new ImageIcon(getClass().getResource("/text_box.png"));
        textBox[bgNum].setIcon(boxIcon);
        textBox[bgNum].setBounds(318, 680, 1270, 320);
        textAreaBox[bgNum].setBackground(new Color(0, 0, 0, 0));
        textAreaBox[bgNum].setOpaque(false);
        textAreaBox[bgNum].setBounds(410, 740, 1000, 200);
        textAreaBox[bgNum].setFont(new java.awt.Font("Courier New", 0, 30));
        textAreaBox[bgNum].setForeground(Color.yellow);
        textAreaBox[bgNum].setBorder(null);
        textAreaBox[bgNum].setEditable(false);
        textAreaBox[bgNum].setWrapStyleWord(true);
        textAreaBox[bgNum].setLineWrap(true);
        textAreaBox2[bgNum].setBackground(new Color(0, 0, 0, 0));
        textAreaBox2[bgNum].setOpaque(false);
        textAreaBox2[bgNum].setBounds(410, 790, 1000, 200);
        textAreaBox2[bgNum].setFont(new java.awt.Font("Courier New", 0, 30));
        textAreaBox2[bgNum].setForeground(Color.white);
        textAreaBox2[bgNum].setBorder(null);
        textAreaBox2[bgNum].setEditable(false);
        textAreaBox2[bgNum].setWrapStyleWord(true);
        textAreaBox2[bgNum].setLineWrap(true);

        textButton[bgNum].setBackground(new Color(0, 0, 0));
        textButton[bgNum].setBounds(1426, 920, 64, 26);
        textButton[bgNum].setFont(new Font("Segoe UI", 2, 14)); // NOI18N
        textButton[bgNum].setForeground(new Color(255, 255, 255));
        textButton[bgNum].setText("Chiudi");
        textButton[bgNum].setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED,
                Color.lightGray, Color.white, Color.lightGray, Color.white));
        textButton[bgNum].setContentAreaFilled(false);
        textButton[bgNum].addActionListener(actHandler);
        textButton[bgNum].setActionCommand("continueTextScene" + bgNum);
        icon[bgNum].setBounds(1400, 790, 100, 100);

        //DIALOGHI A SCELTA
        dialogueButton1[bgNum] = new JRadioButton();
        dialogueButton2[bgNum] = new JRadioButton();
        dialogueButton3[bgNum] = new JRadioButton();
        dialogueButton4[bgNum] = new JRadioButton();

        dialogueButton1[bgNum].setBounds(410, 750, 600, 50);
        dialogueButton2[bgNum].setBounds(960, 750, 600, 50);
        dialogueButton3[bgNum].setBounds(410, 860, 600, 50);
        dialogueButton4[bgNum].setBounds(960, 860, 600, 50);
        dialogueButton1[bgNum].setSelected(false);
        dialogueButton2[bgNum].setSelected(false);
        dialogueButton3[bgNum].setSelected(false);
        dialogueButton4[bgNum].setSelected(false);
        dialogueButton1[bgNum].setForeground(Color.white);
        dialogueButton2[bgNum].setForeground(Color.white);
        dialogueButton3[bgNum].setForeground(Color.white);
        dialogueButton4[bgNum].setForeground(Color.white);
        dialogueButton1[bgNum].setBackground(new Color(0, 0, 0));
        dialogueButton1[bgNum].setOpaque(false);
        dialogueButton2[bgNum].setBackground(new Color(0, 0, 0));
        dialogueButton2[bgNum].setOpaque(false);
        dialogueButton3[bgNum].setBackground(new Color(0, 0, 0));
        dialogueButton3[bgNum].setOpaque(false);
        dialogueButton4[bgNum].setBackground(new Color(0, 0, 0));
        dialogueButton4[bgNum].setOpaque(false);

        dialogueButton1[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton2[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton3[bgNum].setFont(new Font("Courier New", 0, 28));
        dialogueButton4[bgNum].setFont(new Font("Courier New", 0, 28));

        ButtonGroup group = new ButtonGroup();
        group.add(dialogueButton1[bgNum]);
        group.add(dialogueButton2[bgNum]);
        group.add(dialogueButton3[bgNum]);
        group.add(dialogueButton4[bgNum]);

        //visibility
        textBox[bgNum].setVisible(false);
        textAreaBox[bgNum].setVisible(false);
        textAreaBox2[bgNum].setVisible(false);
        textButton[bgNum].setVisible(false);
        continueDialogue[bgNum].setVisible(false);
        dialogueButton1[bgNum].setVisible(false);
        dialogueButton2[bgNum].setVisible(false);
        dialogueButton3[bgNum].setVisible(false);
        dialogueButton4[bgNum].setVisible(false);
        detectiveDestra[bgNum].setVisible(false);
        detectiveSinistra[bgNum].setVisible(false);
        icon[bgNum].setVisible(false);

        bgPanel[bgNum].add(icon[bgNum]);
        bgPanel[bgNum].add(dialogueButton4[bgNum]);
        bgPanel[bgNum].add(dialogueButton3[bgNum]);
        bgPanel[bgNum].add(dialogueButton2[bgNum]);
        bgPanel[bgNum].add(dialogueButton1[bgNum]);
        bgPanel[bgNum].add(continueDialogue[bgNum]);
        bgPanel[bgNum].add(textButton[bgNum]);
        bgPanel[bgNum].add(textAreaBox[bgNum]);
        bgPanel[bgNum].add(textAreaBox2[bgNum]);
        bgPanel[bgNum].add(textBox[bgNum]);
        bgPanel[bgNum].add(detectiveDestra[bgNum]);
        bgPanel[bgNum].add(detectiveSinistra[bgNum]);
    }

    /**
     * Crea una generica freccia (button)
     * 
     * @param bgNum numero panel dove crearla
     * @param x
     * @param y
     * @param arrowFileName
     * @param command action command associato
     * @param actHandler indica quale sottoclasse di ActionHandler utilizzare
     */
    public void createArrowButton(int bgNum, int x, int y, String arrowFileName, String command, ActionHandler actHandler) {

        ImageIcon arrowIcon = new ImageIcon(getClass().getResource(arrowFileName));

        JButton arrowButton = new JButton();
        arrowButton.setBounds(x, y, 150, 150);
        arrowButton.setBackground(null);
        arrowButton.setContentAreaFilled(false);
        arrowButton.setFocusPainted(false);
        arrowButton.setIcon(arrowIcon);
        arrowButton.addActionListener(actHandler);
        arrowButton.setActionCommand(command);
        arrowButton.setBorderPainted(false);

        bgPanel[bgNum].add(arrowButton);
    }

    /**
     * Crea un generico oggetto grafico con cui è possibile interagire (NPC o item)
     *
     * @param bgNum
     * @param objx
     * @param objy
     * @param objWidth
     * @param objHeight
     * @param objFileName
     * @param choice1Name 
     * @param choice2Name 
     * @param choice3Name 
     * @param choice1Command primo action command associato al primo item del pop up menu
     * @param Choice2Command terzo action command associato al terzo item del pop up menu
     * @param Choice3Command terzo action command associato al terzo item del pop up menu
     * @param actHandler
     */
    public void createObject(int bgNum, int objx, int objy, int objWidth, int objHeight, String objFileName,
            String choice1Name, String choice2Name, String choice3Name, String choice1Command, String Choice2Command, String Choice3Command, ActionHandler actHandler) {

        // CREATE POP MENU
        JPopupMenu popMenu = new JPopupMenu();
        // CREATE POP MENU ITEMS
        JMenuItem menuItem[] = new JMenuItem[3];
        menuItem[1] = new JMenuItem(choice1Name);
        menuItem[1].addActionListener(actHandler);
        menuItem[1].setActionCommand(choice1Command);
        popMenu.add(menuItem[1]);
        popMenu.setSize(40, 40);

        menuItem[2] = new JMenuItem(choice2Name);
        menuItem[2].addActionListener(actHandler);
        menuItem[2].setActionCommand(Choice2Command);
        popMenu.add(menuItem[2]);

        // CREATE OBJECTS
        JLabel objectLabel = new JLabel();
        objectLabel.setBounds(objx, objy, objWidth, objHeight);
        //objectLabel.setOpaque(true);
        //objectLabel.setBackground(Color.blue);

        ImageIcon objectIcon = new ImageIcon(getClass().getResource(objFileName));
        objectLabel.setIcon(objectIcon);

        objectLabel.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    popMenu.show(objectLabel, e.getX(), e.getY());
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

        });

        bgPanel[bgNum].add(objectLabel);

    }

    /**
     * Crea la scena iniziale di ogni mappa
     * <ul>
     * <li> placeDescription4 serve per il settare il dialogo finale
     *
     * @param bgNum Numero della scena
     * @param objFileName nome file background
     * @param choice1Name testo 1 titolo
     * @param choice2Name testo 2 titolo
     * @param choice3Name testo 3 titolo
     * @param actHandler gestiore azioni
     * @param objx2
     * @param length4
     * @param objx4
     *
     */

    public void createStartDay(int bgNum, String objFileName,
            String choice1Name, String choice2Name, String choice3Name, ActionHandler actHandler, int objx2, int length4, int objx4) {

        placeDescription1[bgNum] = new JTextField();
        placeDescription2[bgNum] = new JTextField();
        placeDescription3[bgNum] = new JTextField();
        placeDescription4[bgNum] = new JTextField();//txtfield 
        go[bgNum] = new JButton();
        go[bgNum].setBackground(new Color(0, 0, 0));
        go[bgNum].setBounds(920, 600, 64, 26);
        go[bgNum].setFont(new Font("Segoe UI", 2, 14)); // NOI18N
        go[bgNum].setForeground(new Color(255, 255, 255));
        go[bgNum].setText("Continua");
        go[bgNum].setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED,
                Color.lightGray, Color.white, Color.lightGray, Color.white));
        go[bgNum].setContentAreaFilled(false);
        go[bgNum].addActionListener(actHandler);
        go[bgNum].setActionCommand(objFileName);

        placeDescription1[bgNum].setEditable(false);
        placeDescription1[bgNum].setBackground(new java.awt.Color(0, 0, 0));
        placeDescription1[bgNum].setFont(new java.awt.Font("Californian FB", 3, 48)); // NOI18N
        placeDescription1[bgNum].setForeground(new java.awt.Color(255, 255, 255));
        placeDescription1[bgNum].setText(choice1Name);
        placeDescription1[bgNum].setBorder(null);
        placeDescription1[bgNum].setBounds(670, 200, 800, 40);

        placeDescription2[bgNum].setEditable(false);
        placeDescription2[bgNum].setBackground(new java.awt.Color(0, 0, 0));
        placeDescription2[bgNum].setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        placeDescription2[bgNum].setForeground(new java.awt.Color(255, 255, 255));
        placeDescription2[bgNum].setText(choice2Name);
        placeDescription2[bgNum].setBorder(null);
        placeDescription2[bgNum].setBounds(objx2, 350, 800, 50);

        placeDescription3[bgNum].setEditable(false);
        placeDescription3[bgNum].setBackground(new java.awt.Color(0, 0, 0));
        placeDescription3[bgNum].setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        placeDescription3[bgNum].setForeground(new java.awt.Color(255, 255, 255));
        placeDescription3[bgNum].setText(choice3Name);
        placeDescription3[bgNum].setBorder(null);
        placeDescription3[bgNum].setBounds(730, 450, 1100, 40);

        placeDescription4[bgNum].setEditable(false);
        placeDescription4[bgNum].setBackground(new java.awt.Color(0, 0, 0));
        placeDescription4[bgNum].setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        placeDescription4[bgNum].setForeground(new java.awt.Color(255, 255, 255));
        placeDescription4[bgNum].setBorder(null);
        placeDescription4[bgNum].setBounds(objx4, 450, length4, 150);
        placeDescription4[bgNum].setVisible(true);

        bgPanel[bgNum].add(placeDescription1[bgNum]);
        bgPanel[bgNum].add(placeDescription2[bgNum]);
        bgPanel[bgNum].add(placeDescription3[bgNum]);
        bgPanel[bgNum].add(placeDescription4[bgNum]);
        bgPanel[bgNum].add(go[bgNum]);

        bgPanel[bgNum].add(bgLabel[bgNum]);
    }

    /**
     * Metodo che crea graficamente tutte le scene visibili del gioco
     *
     * @throws FileNotFoundException
     * @throws IOException
     */
    public void generateScenes() throws FileNotFoundException, IOException {

        //SCENA 1 -> DINING ROOM
        createScene(1, 0, -10, "/diningroommod.png", gh.getActHandler1());
        createTextBox(1, gh.getActHandler1());

        createArrowButton(1, 1750, 500, "/right_arrow.png", "goToCorridorFromDRoom", gh.getActHandler1());
        createObject(1, 200, 220, 200, 700, "", "Parla", "Osserva", "", "TalkDolly", "ObserveDolly", "", gh.getActHandler1());
        createObject(1, 1550, 210, 220, 700, "", "Parla", "Osserva", "", "TalkJane", "ObserveJane", "", gh.getActHandler1());
        bgPanel[1].add(bgLabel[1]);

        //SCENA 2 -> CORRIDOIO PIANO TERRA
        createScene(2, 352, 0, "/corridoio1.png", gh.getActHandler1());
        createTextBox(2, gh.getActHandler1());
        createObject(2, 620, 300, 150, 650, "", "Entra", "Osserva", "", "WestRoomCorridor1", "ObserveDiningRoom", "", gh.getActHandler1());
        createObject(2, 1215, 300, 150, 650, "", "Entra", "Osserva", "", "EastRoomCorridor1", "ObserveLivingRoom", "", gh.getActHandler1());
        createObject(2, 850, 350, 300, 500, "", "Sali al piano superiore", "", "", "StaircaseUP1", "", "", gh.getActHandler1());
        createArrowButton(2, 900, 900, "/hotelicon.png", "goToHotel", gh.getActHandler1());

        setVisibleObject(2, 16, false);

        bgPanel[2].add(bgLabel[2]);

        //SCENA 3 -> LIVING ROOM 
        createScene(3, 0, -10, "/livingroom.png", gh.getActHandler1());
        createTextBox(3, gh.getActHandler1());
        createArrowButton(3, 10, 500, "/left_arrow.png", "goToCorridorFromLRoom", gh.getActHandler1());
        createObject(3, 250, 250, 200, 650, "", "Parla", "Osserva", "puntagli il ferro", "TalkLorrimer", "ObserveLorrimer", "", gh.getActHandler1());
        bgPanel[3].add(bgLabel[3]);

        //SCENA 4 -> CORRIDOIO PRIMO PIANO
        createScene(4, 352, 0, "/corridoio2.png", gh.getActHandler1());
        createTextBox(4, gh.getActHandler1());
        createArrowButton(4, 850, 850, "/down_arrow.png", "StaircaseDown1", gh.getActHandler1());
        createObject(4, 550, 300, 150, 650, "", "Entra", "Osserva", "", "WestRoomCorridor2", "ObserveStudy", "", gh.getActHandler1());
        createObject(4, 1120, 300, 150, 650, "", "Entra", "Osserva", "", "EastRoomCorridor2", "ObserveLibrary", "", gh.getActHandler1());
        bgPanel[4].add(bgLabel[4]);

        //SCENA 5 -> STUDIO
        createScene(5, 0, -10, "/studio.png", gh.getActHandler1());
        createTextBox(5, gh.getActHandler1());
        createArrowButton(5, 1750, 500, "/right_arrow.png", "goToCorridorFromStudy", gh.getActHandler1());
        createObject(5, 390, 250, 200, 700, "", "Parla", "Osserva", "", "TalkBasil", "ObserveBasil", "", gh.getActHandler1());
        createObject(5, 1350, 250, 220, 700, "", "Parla", "Osserva", "", "TalkABantry", "ObserveABantry", "", gh.getActHandler1());
        bgPanel[5].add(bgLabel[5]);

        //SCENA 6 -> BIBLIOTECA
        createScene(6, 0, -10, "/Library.png", gh.getActHandler1());
        createTextBox(6, gh.getActHandler1());
        createArrowButton(6, 10, 500, "/left_arrow.png", "goToCorridorFromLibrary", gh.getActHandler1());
        createObject(6, 250, 700, 600, 170, "", "Osserva", "Ispeziona", "", "ObserveBody", "AnalizeBody", "", gh.getActHandler1());
        createObject(6, 1000, 400, 220, 500, "", "Parla", "Osserva", "", "TalkHaydoc", "ObserveHaydoc", "", gh.getActHandler1());
        bgPanel[6].add(bgLabel[6]);

        //SCENA 7 -> HOTEL BLACK SCREEN
        createScene(7, 0, 0, "", gh.getActHandler1());
        createTextBox(7, gh.getActHandler2());
        createStartDay(7, "enterHotel", "St. Mary Mead, Ottobre 1982", "Majestic Hotel", "Lussuoso Hotel della contea", gh.getActHandler2(), 800, 1100, 600);

        //SCENA 8 -> RECEPTION
        createScene(8, 0, -10, "/receptionhotel.png", gh.getActHandler2());
        createTextBox(8, gh.getActHandler2());
        createArrowButton(8, 1750, 500, "/homeicon.png", "goToGossingtonHall", gh.getActHandler2());
        createArrowButton(8, 10, 500, "/left_arrow.png", "goToHallFromReception", gh.getActHandler2());
        createObject(8, 1000, 250, 200, 400, "", "Parla", "Osserva", "", "TalkOwner", "ObserveOwner", "", gh.getActHandler2());
        createArrowButton(8, 1750, 800, "/policestationicon.png", "goToPoliceStation", gh.getActHandler2());

        bgPanel[8].add(bgLabel[8]);

        //SCENA 9 -> SALA DA BALLO
        createScene(9, 0, 0, "/hall.png", gh.getActHandler2());
        createTextBox(9, gh.getActHandler2());
        createArrowButton(9, 1750, 500, "/right_arrow.png", "goToReceptionFromHall", gh.getActHandler2());
        createArrowButton(9, 10, 500, "/left_arrow.png", "StaircaseUP2", gh.getActHandler2());
        createObject(9, 330, 600, 150, 330, "", "Parla", "Osserva", "", "TalkJosephine", "ObserveJosephine", "", gh.getActHandler2());
        createObject(9, 1430, 600, 150, 330, "", "Parla", "Osserva", "", "TalkRamon", "ObserveRamon", "", gh.getActHandler2());
        bgPanel[9].add(bgLabel[9]);

        //SCENA 10 -> CORRIDOIO
        createScene(10, 352, -10, "/corridoiohotel.png", gh.getActHandler2());
        createTextBox(10, gh.getActHandler2());
        createArrowButton(10, 850, 850, "/down_arrow.png", "StaircaseDown2", gh.getActHandler2());
        createObject(10, 360, 100, 200, 850, "", "Bussa", "Entra (senza bussare è maleducazione...)", "", "KnockRoom", "goToRoomFromCorridor", "", gh.getActHandler2());
        bgPanel[10].add(bgLabel[10]);

        //SCENA 11 -> ROOM
        createScene(11, 0, -10, "/bedroom.png", gh.getActHandler2());
        createTextBox(11, gh.getActHandler2());
        createArrowButton(11, 10, 500, "/left_arrow.png", "goToVeranda", gh.getActHandler2());
        createArrowButton(11, 1750, 500, "/right_arrow.png", "goToCorridor", gh.getActHandler2());
        createObject(11, 650, 200, 200, 700, "", "Parla", "Osserva", "", "TalkJefferson", "ObserveJefferson", "", gh.getActHandler2());
        bgPanel[11].add(bgLabel[11]);

        //SCENA 12 -> VERANDA
        createScene(12, 0, -10, "/veranda.png", gh.getActHandler2());
        createTextBox(12, gh.getActHandler2());
        createArrowButton(12, 1750, 500, "/right_arrow.png", "goToRoomFromVeranda", gh.getActHandler2());
        createObject(12, 200, 70, 200, 830, "", "Parla", "Osserva", "", "TalkMark", "ObserveMark", "", gh.getActHandler2());
        createObject(12, 490, 600, 140, 140, "/bill.png", "Osserva", "Raccogli", "", "observeBill", "takeBill", "", gh.getActHandler2());
        bgPanel[12].add(bgLabel[12]);

        //SCENA 13 -> STAZIONE DI POLIZIA BLACK SCREEN
        createScene(13, 0, 0, "", gh.getActHandler3());
        createTextBox(13, gh.getActHandler3());
        createStartDay(13, "enterPoliceStation", "St. Mary Mead, Ottobre 1982", "Stazione di Polizia", "", gh.getActHandler3(), 780, 1100, 600);

        //SCENA 14 -> POLICE STATION
        createScene(14, 0, -10, "/stazione_polizia.png", gh.getActHandler3());
        createTextBox(14, gh.getActHandler3());
        createArrowButton(14, 10, 500, "/left_arrow.png", "goToInterrogation", gh.getActHandler3());
        createObject(14, 380, 250, 250, 400, "", "Parla", "Osserva", "", "TalkMelchett", "ObserveMelchett", "", gh.getActHandler3());
        createObject(14, 1220, 230, 200, 400, "", "Parla", "Osserva", "", "TalkPalk", "ObservePalk", "", gh.getActHandler3());
        createArrowButton(14, 850, 850, "/hotelicon.png", "goToReceptionFromStation", gh.getActHandler3());
        bgPanel[14].add(bgLabel[14]);

        //SCENA 15 -> STANZA DEGLI INTERROGATORI
        createScene(15, 0, -10, "/interrogatorio.png", gh.getActHandler3());
        createTextBox(15, gh.getActHandler3());
        createArrowButton(15, 1750, 500, "/right_arrow.png", "goToStationFromInterrogation", gh.getActHandler3());
        createObject(15, 870, 230, 135, 135, "/uncertainty.png", "Interroga", "", "", "chooseSuspected", "", "", gh.getActHandler3());
        createObject(15, 280, 280, 290, 770, "/arthurpixel.png", "Parla", "Osserva", "", "TalkArthur", "ObserveArthur", "", gh.getActHandler3());
        createObject(15, 280, 280, 290, 770, "/basilsprite.png", "Parla", "Osserva", "", "TalkBasil", "ObserveBasil", "", gh.getActHandler3());
        createObject(15, 200, 270, 547, 880, "/scenainterrogatorio3.png", "Parla", "Osserva", "", "TalkMarkJosephine", "ObserveMarkJosephine", "", gh.getActHandler3());

        setVisibleObject(15, 15, false);
        setVisibleObject(15, 16, false);
        setVisibleObject(15, 17, false);

        bgPanel[15].add(bgLabel[15]);

        //SCENA 16 -> STAZIONE DI POLIZIA BLACK SCREEN
        createScene(16, 0, 0, "", gh.getActHandler3());
        createTextBox(16, gh.getActHandler3());
        createStartDay(16, "continueTrueEnding", "", "", "", gh.getActHandler3(), 620, 1500, 400);

        //SCENA 17 -> STAZIONE DI POLIZIA BLACK SCREEN
        createScene(17, 0, 0, "", gh.getActHandler3());
        createTextBox(17, gh.getActHandler3());

        createStartDay(17, "continueFalseEnding", "", "", "", gh.getActHandler3(), 780, 1500, 700);

    }

    /**
     * Setta la visibilità di uno specifico oggetto
     *
     * @param bgNum
     * @param idx
     * @param bool
     */
    public void setVisibleObject(int bgNum, int idx, boolean bool) {
        Component[] object = bgPanel[bgNum].getComponents();
        object[idx].setVisible(bool);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton cmdContinua;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtTitle1;
    private javax.swing.JTextField txtTitle2;
    private javax.swing.JTextField txtTitle3;
    // End of variables declaration//GEN-END:variables

}
