/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Image;
import javax.swing.JLabel;

/**
 *
 * @author tom
 */
public class InventoryDialog extends javax.swing.JDialog {

    /**
     * Creates new form InventoryDialog
     */
    public InventoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        item_1 = new javax.swing.JButton();
        item_2 = new javax.swing.JButton();
        item_3 = new javax.swing.JButton();
        item_4 = new javax.swing.JButton();
        item_5 = new javax.swing.JButton();
        item_6 = new javax.swing.JButton();
        item_7 = new javax.swing.JButton();
        item_8 = new javax.swing.JButton();
        item_9 = new javax.swing.JButton();
        item_10 = new javax.swing.JButton();
        item_11 = new javax.swing.JButton();
        item_12 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item_1.setForeground(new java.awt.Color(255, 255, 255));
        item_1.setText("ITEM 1");
        item_1.setContentAreaFilled(false);
        getContentPane().add(item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 100));

        item_2.setForeground(new java.awt.Color(255, 255, 255));
        item_2.setText("ITEM 2");
        item_2.setContentAreaFilled(false);
        getContentPane().add(item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 100, 100));

        item_3.setForeground(new java.awt.Color(255, 255, 255));
        item_3.setText("ITEM 3");
        item_3.setContentAreaFilled(false);
        getContentPane().add(item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 100, 100));

        item_4.setForeground(new java.awt.Color(255, 255, 255));
        item_4.setText("ITEM 4");
        item_4.setContentAreaFilled(false);
        getContentPane().add(item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 100, 100));

        item_5.setForeground(new java.awt.Color(255, 255, 255));
        item_5.setText("ITEM 5");
        item_5.setToolTipText("");
        item_5.setContentAreaFilled(false);
        getContentPane().add(item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 100));

        item_6.setForeground(new java.awt.Color(255, 255, 255));
        item_6.setText("ITEM 6");
        item_6.setContentAreaFilled(false);
        getContentPane().add(item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, 100));

        item_7.setForeground(new java.awt.Color(255, 255, 255));
        item_7.setText("ITEM 7");
        item_7.setContentAreaFilled(false);
        getContentPane().add(item_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 100));

        item_8.setForeground(new java.awt.Color(255, 255, 255));
        item_8.setText("ITEM 8");
        item_8.setContentAreaFilled(false);
        getContentPane().add(item_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 100, 100));

        item_9.setForeground(new java.awt.Color(255, 255, 255));
        item_9.setText("ITEM 9");
        item_9.setContentAreaFilled(false);
        getContentPane().add(item_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 100, 100));

        item_10.setForeground(new java.awt.Color(255, 255, 255));
        item_10.setText("ITEM 10");
        item_10.setContentAreaFilled(false);
        getContentPane().add(item_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 100, 100));

        item_11.setForeground(new java.awt.Color(255, 255, 255));
        item_11.setText("ITEM 11");
        item_11.setContentAreaFilled(false);
        getContentPane().add(item_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 100, 100));

        item_12.setForeground(new java.awt.Color(255, 255, 255));
        item_12.setText("ITEM 12");
        item_12.setContentAreaFilled(false);
        getContentPane().add(item_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 100, 100));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brown-leather.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InventoryDialog dialog = new InventoryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton item_1;
    private javax.swing.JButton item_10;
    private javax.swing.JButton item_11;
    private javax.swing.JButton item_12;
    private javax.swing.JButton item_2;
    private javax.swing.JButton item_3;
    private javax.swing.JButton item_4;
    private javax.swing.JButton item_5;
    private javax.swing.JButton item_6;
    private javax.swing.JButton item_7;
    private javax.swing.JButton item_8;
    private javax.swing.JButton item_9;
    // End of variables declaration//GEN-END:variables
}
