/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import db.DataHandler;
import static game.Main.listItem;
import static game.Main.listNPC;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import type.Item;

/**
 *
 * @author tom
 */
public class InventoryDialog extends javax.swing.JDialog {

    GameHandler gh;
    ActionHandler invHandler = new InventoryHandler(gh);

    
    /**
     * Creates new form InventoryDialog
     *
     * @param parent
     * @param modal
     */
    public InventoryDialog(java.awt.Frame parent, boolean modal,GameHandler gh) {
        super(parent, modal);
        this.gh = gh;
        initComponents();

    }

    public JButton getItem_1() {
        return item_1;
    }

    public JButton getItem_2() {
        return item_2;
    }

    public JButton getItem_3() {
        return item_3;
    }

    public void setItem_1(JButton item_1) {

        this.item_1 = item_1;
    }

    public void setItem_2(JButton item_2) {

        this.item_2 = item_2;

    }

    public JButton getItem_10() {
        return item_10;
    }

    public void setItem_10(JButton item_10) {

        this.item_10 = item_10;

    }

    public JButton getItem_11() {
        return item_11;
    }

    public void setItem_11(JButton item_11) {

        this.item_11 = item_11;

    }

    public JButton getItem_12() {
        return item_12;
    }

    public void setItem_12(JButton item_12) {
        this.item_12 = item_12;
    }

    public JButton getItem_4() {
        return item_4;
    }

    public void setItem_4(JButton item_4) {
        this.item_4 = item_4;
    }

    public JButton getItem_5() {
        return item_5;
    }

    public void setItem_5(JButton item_5) {
        this.item_5 = item_5;
    }

    public JButton getItem_6() {
        return item_6;
    }

    public void setItem_6(JButton item_6) {
        this.item_6 = item_6;
    }

    public JButton getItem_7() {
        return item_7;
    }

    public void setItem_7(JButton item_7) {
        this.item_7 = item_7;
    }

    public JButton getItem_9() {
        return item_9;
    }

    public void setItem_9(JButton item_9) {
        this.item_9 = item_9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        item_1 = new javax.swing.JButton();
        item_2 = new javax.swing.JButton();
        item_3 = new javax.swing.JButton();
        item_4 = new javax.swing.JButton();
        item_5 = new javax.swing.JButton();
        item_6 = new javax.swing.JButton();
        item_7 = new javax.swing.JButton();
        item_8 = new javax.swing.JButton();
        item_9 = new javax.swing.JButton();
        item_10 = new javax.swing.JButton();
        item_11 = new javax.swing.JButton();
        item_12 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        popupMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                popupMenu1KeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item_1.setForeground(new java.awt.Color(255, 255, 255));
        item_1.setText("ITEM 1");
        createObject(60, 30, 128, 128, "", "Osserva", "Butta", "ObserveItem_1", "",invHandler,item_1);
        item_1.setComponentPopupMenu(jPopupMenu2);
        item_1.setContentAreaFilled(false);
        item_1.setMinimumSize(new java.awt.Dimension(128, 128));
        item_1.setPreferredSize(new java.awt.Dimension(128, 128));
        getContentPane().add(item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 160));
        item_1.setVisible(true);

        item_2.setForeground(new java.awt.Color(255, 255, 255));
        item_2.setText("ITEM 2");
        item_2.setContentAreaFilled(false);
        getContentPane().add(item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 160));
        createObject(270, 30, 128, 128, "", "Osserva", "Butta", "ObserveItem_2", "",invHandler,item_2);
        item_2.setVisible(false);

        item_3.setForeground(new java.awt.Color(255, 255, 255));
        item_3.setText("ITEM 3");
        item_3.setContentAreaFilled(false);
        getContentPane().add(item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 170, 160));

        item_4.setForeground(new java.awt.Color(255, 255, 255));
        item_4.setText("ITEM 4");
        item_4.setContentAreaFilled(false);
        getContentPane().add(item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 170, 160));

        item_5.setForeground(new java.awt.Color(255, 255, 255));
        item_5.setText("ITEM 5");
        item_5.setToolTipText("");
        item_5.setContentAreaFilled(false);
        getContentPane().add(item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 160));

        item_6.setForeground(new java.awt.Color(255, 255, 255));
        item_6.setText("ITEM 6");
        item_6.setContentAreaFilled(false);
        getContentPane().add(item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 170, 160));

        item_7.setForeground(new java.awt.Color(255, 255, 255));
        item_7.setText("ITEM 7");
        item_7.setContentAreaFilled(false);
        getContentPane().add(item_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 170, 160));

        item_8.setForeground(new java.awt.Color(255, 255, 255));
        item_8.setText("ITEM 8");
        item_8.setContentAreaFilled(false);
        getContentPane().add(item_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 170, 160));

        item_9.setForeground(new java.awt.Color(255, 255, 255));
        item_9.setText("ITEM 9");
        item_9.setContentAreaFilled(false);
        getContentPane().add(item_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 170, 160));

        item_10.setForeground(new java.awt.Color(255, 255, 255));
        item_10.setText("ITEM 10");
        item_10.setContentAreaFilled(false);
        getContentPane().add(item_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 100, 100));

        item_11.setForeground(new java.awt.Color(255, 255, 255));
        item_11.setText("ITEM 11");
        item_11.setContentAreaFilled(false);
        getContentPane().add(item_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 190, 210));

        item_12.setForeground(new java.awt.Color(255, 255, 255));
        item_12.setText("ITEM 12");
        item_12.setContentAreaFilled(false);
        getContentPane().add(item_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 180, 190));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brown-leather.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popupMenu1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_popupMenu1KeyPressed

    public void createObject(int objx, int objy, int objWidth, int objHeight, String objFileName,
            String choice1Name, String choice2Name, String choice1Command, String Choice2Command, ActionHandler actHandler, JButton item) {

        // CREATE POP MENU
        JPopupMenu popMenu = new JPopupMenu();
        // CREATE POP MENU ITEMS
        JMenuItem menuItem[] = new JMenuItem[3]; // Use [1],[2],[3]
        menuItem[1] = new JMenuItem(choice1Name);
        menuItem[1].addActionListener(actHandler);
        menuItem[1].setActionCommand(choice1Command);
        popMenu.add(menuItem[1]);

        menuItem[2] = new JMenuItem(choice2Name);
        menuItem[2].addActionListener(actHandler);
        menuItem[2].setActionCommand(Choice2Command);
        popMenu.add(menuItem[2]);

        // CREATE OBJECTS
        item.setBounds(objx, objy, objWidth, objHeight);
        item.setOpaque(false);
        //objectLabel.setBackground(Color.blue);

        ImageIcon objectIcon = new ImageIcon(getClass().getResource(objFileName));
        item.setIcon(objectIcon);

        item.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    popMenu.show(item, e.getX(), e.getY());
                }
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }

        });

    }

    public void observeItem(Item item,String itemName) {
        //TODO file
        item = DataHandler.ItemFinder(listItem, itemName);
        JOptionPane.showMessageDialog(this,item.getDescription());
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    public javax.swing.JButton item_1;
    private javax.swing.JButton item_10;
    private javax.swing.JButton item_11;
    private javax.swing.JButton item_12;
    private javax.swing.JButton item_2;
    private javax.swing.JButton item_3;
    private javax.swing.JButton item_4;
    private javax.swing.JButton item_5;
    private javax.swing.JButton item_6;
    private javax.swing.JButton item_7;
    private javax.swing.JButton item_8;
    private javax.swing.JButton item_9;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
